FROM mongo:8.0.17@sha256:9814652e33f0cf8b9fddea8b46dfc9d8e19b130dcfdd7b510ca58bb0d40c8b71

LABEL org.opencontainers.image.source="https://github.com/monotykamary/railway-template-pipeshub"

CMD ["mongod", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
