FROM mongo:8.0.32@sha256:4968f22d0c6c10ef29952f3e807f62872ba22b3312f25803564fbfc08255efc2

LABEL org.opencontainers.image.source="https://github.com/monotykamary/railway-template-pipeshub"

CMD ["mongod", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]
